[package]
name = "vimp"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
js-sys = "0.3.72"
leptos = { version = "0.6.15", features = ["csr", "nightly"] }
regex = "1.11.1"
wasm-bindgen = "0.2.95"
